services:
  winarm:
    image: dockurr/windows
    container_name: win_arm
    # restart: unless-stopped
    environment:
      # VERSION: "https://example.com/win.iso"
      # VERSION: "win7"
      VERSION: "win11e"
      RAM_SIZE: "6G"
      CPU_CORES: "2"
      DISK_SIZE: "32G"
      USERNAME: "dd"
      PASSWORD: "7654321234567"
      LANGUAGE: "Chinese"   
    volumes:
      # - /home/tiny11corex64beta1.iso:/custom.iso
      - /home/win_arm_disk:/storage
      - /home/win_arm_share:/shared
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5000:5000
      - 3389:3389/tcp
      - 3389:3389/udp
      # - 2080:2080/tcp
      # - 2080:2080/udp
    stop_grace_period: 2m
    networks:
      - 1panel-v4v6

networks:
  1panel-v4v6:
    external: true